# For Thundercomm RUBIK Pi 3, the LUN 6 partitions (rubikpi_con, devcfg_full,
# dtb_con) reference *.img payloads (rubikpi_config.img, devcfg_full.img,
# rubikpi_dtso.img, splash.img). The upstream qcomflash class' create_qcomflash_pkg
# whitelist covers *.elf / *.mbn / *.fv / named bins, but not *.img.
#
# Note: bbappend on do_image_qcomflash doesn't propagate because that task is
# dynamically generated by image.bbclass from IMAGE_CMD:qcomflash. Override
# IMAGE_CMD:qcomflash for this machine to wrap the upstream call.

add_rubikpi3_lun6_imgs() {
    QCDIR="${IMGDEPLOYDIR}/${IMAGE_NAME}.qcomflash"
    SRC="${DEPLOY_DIR_IMAGE}/${QCOM_BOOT_FILES_SUBDIR}"
    added=0
    for img in "$SRC"/*.img; do
        [ -e "$img" ] || continue
        install -m 0644 "$img" "$QCDIR/"
        added=1
    done
    if [ "$added" = "1" ]; then
        cd "$QCDIR"
        ${IMAGE_CMD_TAR} --sparse --numeric-owner \
            --transform="s,^\./,${IMAGE_BASENAME}-${MACHINE}/," -cf- . \
            | pigz -p ${BB_NUMBER_THREADS} -9 -n --rsyncable \
            > ${IMGDEPLOYDIR}/${IMAGE_NAME}.qcomflash.tar.gz
        ln -sf ${IMAGE_NAME}.qcomflash.tar.gz \
            ${IMGDEPLOYDIR}/${IMAGE_LINK_NAME}.qcomflash.tar.gz
    fi
}

IMAGE_CMD:qcomflash:qcs6490-thundercomm-rubikpi3 = "create_qcomflash_pkg && add_rubikpi3_lun6_imgs"
